spring:
#  zipkin:
#    base-url: http://localhost:9411
  #引入其他profiles
  profiles:
    include:
      - db

server:
  port: 8002
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck: #把Eureka客户端的健康监测交给/health端点提供
      enabled: false
    serviceUrl:
      defaultZone: http://admin:123456@localhost:1111/eureka/